- name: Check if /boot/firmware/cmdline.txt exists
  ansible.builtin.stat:
    path: /boot/firmware/cmdline.txt
  register: boot_firmware_cmdline_txt

- name: Enable cgroup via boot commandline if not already enabled
  ansible.builtin.lineinfile:
    path: "{{ (boot_firmware_cmdline_txt.stat.exists) | ternary('/boot/firmware/cmdline.txt', '/boot/cmdline.txt') }}"
    backrefs: true
    regexp: '^((?!.*\bcgroup_enable=memory cgroup_memory=1\b).*)$'
    line: '\1 cgroup_enable=memory cgroup_memory=1'
  notify: reboot

- name: Install snap
  ansible.builtin.apt:
    name: snapd
    state: present
    update_cache: yes
