- name: Add user account
  ansible.builtin.user:
    name: "{{ item.username }}"
    group: "{{ item.username }}"
    groups: "{{ item.groups }}"
    append: true
    shell: "{{ item.shell | default('/bin/bash') }}"
    password: !
    state: present
  with_items: "{{ user_accounts }}"
