apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
secretFrom:
  - metadata:
      name: home-assistant-config
      labels:
        app: home-assistant
      annotations:
        kustomize.config.k8s.io/needs-hash: "false"
    type: Opaque
    files:
      - configuration.yaml=./configuration.enc.yaml
