apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namespace: home-assistant

patches:
  - target:
      kind: Ingress
      name: home-assistant
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: home-assistant-sandbox.local
