---
- name: Kubernetes
  hosts: micro_k8s_single_node_hosts
  gather_facts: true
  become: true
  vars:
    microk8s_plugins:
      dns: true
      dashboard: true
      ha-cluster: true
      helm: true
      helm3: true
      hostpath-storage: true
      ingress: true
  roles:
    - microk8s
    - user
    - tools
