@startuml

nwdiag {
	internet [ shape = cloud ]
	internet -- isp_router

	network unsafe {
		address = "192.168.0.x/24"
		color = red

		isp_router [address = ".1"]
		home_router
	}

	network internal {
		address = "192.168.1.x/24"
		color = green

		home_router [address = ".1"]
		j8puk8s01 [address = ".133"]

		laptop01 [address = ".126"]
		pc01 [address = ".108"]

		tv01 [address = ".143"]
	}

	j8puk8s01 -- zigbee_gateway
	zigbee_gateway [address = "USB"]

	network zigbee {
		color = aqua
		electrovalve01
		zigbee_gateway
	}
}

@enduml
