wifi_ssid: ENC[AES256_GCM,data:2cqE7Qh8lp5X/5A=,iv:4RG3e4JURtpf9IL7EudIV+PXVAOUry05LSfiLhQPLfI=,tag:D6IV8kZVZsBH9Y1Qc0Ol+A==,type:str]
wifi_password: ENC[AES256_GCM,data:PVGwKbGiR+tXIeZw46yn,iv:Aym2BS3eFkVPQs2dOX+RGZDG4rsZeFQK+rkGkM7oHSw=,tag:HbxFbXCLa+lG5P4ft5ybQQ==,type:str]
api_key: ENC[AES256_GCM,data:R32amZhMiVo9tga7Yk+EwPiAx6V/i60+pDKJ01nwaFRcSpb4aHErBYz5scU=,iv:pLt1Qka0j44AWxMvaE1lV/nhWIQ8Scv98RtveE5pEpM=,tag:MD24cF134pbxCPDgBmrgfw==,type:str]
ota_password: ENC[AES256_GCM,data:2fiFmNDzyoVGAI4nOUIalUWdazQAnVrHHeM71PishBE=,iv:WcgBDI6IN9tUuFiahxqFpP9H56ISrqTGGebWMK335B4=,tag:iuWJPtCA/utySxU5UHO67w==,type:str]
ap_password: ENC[AES256_GCM,data:hEQlKeW2cRp2zV6M,iv:azIb51X6WPIiDXIA/oB1nG7FUwwiPqhGYxohnAOOrOU=,tag:uMc5f/+7GzwCDnUfo63WrA==,type:str]
sops:
    lastmodified: "2025-08-16T16:25:26Z"
    mac: ENC[AES256_GCM,data:nGeURfZUbVbVxEAjwFJiQSexrFUtQ+wbPbSYC5hXccBB4Pf9qvooZrdlzrChF5CO73EcxsetQPzPpQWMUEutk1lfjEgDHQ8I0ApREcaJzJMaQqpSc/JmSkRZYlRBza6G+ZECesmuzm1ognoABqCIxgyfhI/J8sm7oXLF095f0Qg=,iv:TVQvJdfWIRn4Gld4TbEgVafcuu2xeTOSp9rZ3f5feUQ=,tag:NMPDymBE8I2AYqg3MC3a7w==,type:str]
    pgp:
        - created_at: "2025-08-16T11:38:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DbTkGWe0BjZ4SAQdAcXNJJHbYPM4oLCwKKprjtfub72RlhSFcDgWqHo37cRYw
            3R1SSVh9wFs6me7Q3Jn9nCAglLAcjUJifP/qHxMDTKIEUJxnAxYgmultWL/vvWPg
            1GgBCQIQhxyrMADlOkC1LVXLwxJSjtGQAPbswAGXfJMsTSK081eYyUbZc441lDO4
            DxEZY9nKzH4YTkshW/IELUmZbwFGpwSDYuMlR2bjEjQQ++brbiq57JLpLAwjF8vT
            GMR0wGfB+nNJUg==
            =yoeE
            -----END PGP MESSAGE-----
          fp: F317F8165D3698D667B18A6589F22C693793142F
    unencrypted_suffix: _unencrypted
    version: 3.10.2
